# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrobble < Formula
  desc "Scrobble albums from Discogs to Last.fm from the command line."
  homepage "https://github.com/tommyokeefe/cli-scrobbler"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tommyokeefe/cli-scrobbler/releases/download/0.1.1/scrobble_0.1.1_darwin_amd64.tar.gz"
      sha256 "2305784a16c482130a4455c9b19ac46809dcdea4d4a917cae3ea46a738b1d5e3"

      define_method(:install) do
        bin.install "scrobble"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tommyokeefe/cli-scrobbler/releases/download/0.1.1/scrobble_0.1.1_darwin_arm64.tar.gz"
      sha256 "1170b8db097bdf3202157fd237d4a572f2d633d50436fd297761f7186e08a192"

      define_method(:install) do
        bin.install "scrobble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tommyokeefe/cli-scrobbler/releases/download/0.1.1/scrobble_0.1.1_linux_amd64.tar.gz"
      sha256 "90f65209ab51846cb65c01c4c4fc10d57da2cd7bbaccb9fab9b806b56180e958"
      define_method(:install) do
        bin.install "scrobble"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tommyokeefe/cli-scrobbler/releases/download/0.1.1/scrobble_0.1.1_linux_arm64.tar.gz"
      sha256 "50b51fe45f812eac79fdb9ab24c882e93891e8da05d4c8d7e0a3ed8352992cdc"
      define_method(:install) do
        bin.install "scrobble"
      end
    end
  end

  test do
    system "#{bin}/scrobble", "--help"
  end
end
